name: Build StarlightGUI

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # 允许手动在网页点击触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore StarlightGUI.sln

    - name: Build solution
      run: msbuild StarlightGUI.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: StarlightGUI-Release-x64
        path: |
          **/Release/*.exe
          **/Release/*.dll
